name: Backslashes on Windows with bash as shell
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: bash
        shell: bash
        run: bash
      - name: ls
        shell: bash
        run: ls
