name: Backslashes on Windows with bash as shell
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: ls
        shell: bash
      - run: echo "Hello world!"
        shell: bash
