name: Backslashes on Windows with bash as shell
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: hello
        shell: bash
        run: echo "Hello world!"
      - name: make-dir
        shell: bash
        run: mkdir test_folder
      - name: bash
        shell: bash
        run: ls
