name: Stupid error example
on:
  workflow_dispatch:
  
jobs:
  first_job:
    runs-on: windows-latest
    
    steps:
    - name: STDERR redirect test
      shell: bash
      run: $E = $(Write-Error "oops" 2>&1)
